label OpenIPC SBC-GS
  kernel /boot/Image
  fdt /boot/allwinner/sun50i-h618-orangepi-zero2w.dtb
  append console=ttyS0,115200 console=tty1 consoleblank=0 root=/dev/mmcblk0p1 rootfstype=squashfs ro rootwait cma=256M loglevel=1 init=/init earlycon
