#!/bin/sh
#
# Starts citruspilot.
#

# Allow a few customizations from a config file
test -r /etc/default/citruspilot && . /etc/default/citruspilot

start() {
	printf "Starting citruspilot: "

	start-stop-daemon -S -b -m -q -p /var/run/citruspilot.pid \
		-x /usr/bin/citruspilot.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping citruspilot: "
	start-stop-daemon -K -q -p /var/run/citruspilot.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
